@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImlhdCI6MTc2NTA1MDY1OCwiZXhwIjoxNzY1MDUxNTU4fQ.-icAQnmESX7SgWfXoZBSXA0igkVvgKYWmXMR-O054qY
@ownertoken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc2NTA1MDAzMiwiZXhwIjoxNzY1MDUwOTMyfQ.pK4TftkMcGlC6yFCmWxjZzrHjTSZ5FWB48cRcOiV5bo
@teamcode = GREVUW
### Register a new user
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "username": "alice3",
  "password": "mypassword3"
}
### Login user
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "username": "alice3",
  "password": "mypassword3"
}

### Create a task
POST http://localhost:3000/api/tasks
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Finish project",
  "description": "Complete backend + frontend integration"
}

### Get all tasks
GET http://localhost:3000/api/tasks
Authorization: Bearer {{token}}

### Update task
PUT http://localhost:3000/api/tasks/6
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "completed": true,
  "description": "Finish backend + frontend + tests"
}

### Delete task
DELETE http://localhost:3000/api/tasks/1
Authorization: Bearer {{token}}




###Create a team
POST http://localhost:3000/api/teams
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "My first team",
  "password": "logic"
}

###join user to a team
POST http://localhost:3000/api/teams/join
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "teamCode": "GREVUW",
  "password": "logic"
}

### get all team's tasks
GET http://localhost:3000/api/teams/4/tasks
Authorization: Bearer {{token}}

### add task to a team
POST http://localhost:3000/api/teams/4/tasks
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "Design DB schema 3",
  "description": "Create database schema for the project",
  "completed": false,
  "dueDate": "2025-12-10T00:00:00Z",
  "priority": "high"
}

### edit the task
PUT http://localhost:3000/api/teams/4/tasks/9
Authorization: Bearer {{token}}
Content-Type: application/json 

{
  "title": "Update DB schema 3",
  "completed": true
}

### delete the task from team board
DELETE http://localhost:3000/api/teams/4/tasks/delete/9
Authorization: Bearer {{token}}


### get all team's members
GET http://localhost:3000/api/teams/4/members
Authorization: Bearer {{token}}

### get all users
GET http://localhost:3000/api/users
Authorization: Bearer {{token}}

### add user to the team through userId by owner
POST http://localhost:3000/api/teams/4/join
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "userIdToAdd": 4,
    "role": "member"
}

### change user role by owner
PUT http://localhost:3000/api/teams/4/members/change
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "userIdToChange": 4,
    "role": "owner"
}

### get all user's boards
GET http://localhost:3000/api/teams/all
Authorization: Bearer {{token}}

### remove the user from the team
DELETE http://localhost:3000/api/teams/4/members/delete/2
Authorization: Bearer {{token}}

### Edit current user
PUT http://localhost:3000/api/users/me
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "username": "newUsername",
  "password": "newPassword"
}

### Edit team info
PUT http://localhost:3000/api/teams/1/edit
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "New Team Name",
  "password": "newTeamPassword123"
}


### delete the team
DELETE http://localhost:3000/api/teams/4/delete
Authorization: Bearer {{token}}
